# Generated by Django 4.2.7 on 2025-10-21 23:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('time_limit', models.IntegerField(blank=True, null=True)),
                ('max_attempts', models.IntegerField(default=3)),
                ('passing_score', models.IntegerField(default=70)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='content.lesson')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='content.subject')),
            ],
            options={
                'db_table': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('time_spent', models.IntegerField(default=0)),
                ('is_passed', models.BooleanField(default=False)),
                ('is_abandoned', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.IntegerField()),
                ('average_time_per_question', models.FloatField()),
                ('difficulty_breakdown', models.JSONField(default=dict)),
                ('subject_areas', models.JSONField(default=dict)),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='quizzes.quizattempt')),
            ],
            options={
                'db_table': 'quiz_results',
            },
        ),
        migrations.CreateModel(
            name='QuizAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(default=0)),
                ('total_completions', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('pass_rate', models.FloatField(default=0)),
                ('average_time', models.FloatField(default=0)),
                ('difficulty_distribution', models.JSONField(default=dict)),
                ('common_mistakes', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='quizzes.quiz')),
            ],
            options={
                'db_table': 'quiz_analytics',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TRUE_FALSE', 'True/False'), ('MATCHING', 'Matching'), ('FILL_IN_BLANK', 'Fill in the Blank'), ('SHORT_ANSWER', 'Short Answer')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField(default=1)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('difficulty_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_earned', models.FloatField(default=0)),
                ('time_spent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('current_question_index', models.IntegerField(default=0)),
                ('answers_data', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quizzes.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_sessions',
                'indexes': [models.Index(fields=['student'], name='quiz_sessio_student_ff80b3_idx'), models.Index(fields=['quiz'], name='quiz_sessio_quiz_id_3af531_idx'), models.Index(fields=['session_key'], name='quiz_sessio_session_58ee3a_idx'), models.Index(fields=['is_active'], name='quiz_sessio_is_acti_1903ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('difficulty_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='quizzes.quizattempt')),
            ],
            options={
                'db_table': 'quiz_feedback',
                'unique_together': {('attempt',)},
            },
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student'], name='quiz_attemp_student_bf871b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz'], name='quiz_attemp_quiz_id_3756b1_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['completed_at'], name='quiz_attemp_complet_f97b11_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['is_passed'], name='quiz_attemp_is_pass_93f66a_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['started_at'], name='quiz_attemp_started_8d6002_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanalytics',
            unique_together={('quiz',)},
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['subject'], name='quizzes_subject_4f4408_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['grade_level'], name='quizzes_grade_l_2fea06_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_active'], name='quizzes_is_acti_659c37_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['created_by'], name='quizzes_created_02cca3_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz'], name='questions_quiz_id_387544_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['order_index'], name='questions_order_i_885f22_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='questions_is_acti_ba6b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty_level'], name='questions_difficu_3585ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt'], name='answers_attempt_022a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='answers_questio_3d2018_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_correct'], name='answers_is_corr_b054e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
    ]
