# Generated by Django 4.2.7 on 2025-10-21 23:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lessons', models.IntegerField(default=0)),
                ('completed_lessons', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_progress', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='content.subject')),
            ],
            options={
                'db_table': 'subject_progress',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['student'], name='subject_pro_student_faaf3f_idx'), models.Index(fields=['subject'], name='subject_pro_subject_b46d1a_idx'), models.Index(fields=['student', 'subject'], name='subject_pro_student_6ea870_idx'), models.Index(fields=['last_activity'], name='subject_pro_last_ac_fdeebf_idx')],
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused')], default='NOT_STARTED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent', models.IntegerField(default=0)),
                ('score', models.FloatField(blank=True, null=True)),
                ('last_position', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='content.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_progress',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['student'], name='student_pro_student_c8437a_idx'), models.Index(fields=['lesson'], name='student_pro_lesson__e63e90_idx'), models.Index(fields=['status'], name='student_pro_status_14a99c_idx'), models.Index(fields=['completed_at'], name='student_pro_complet_57b035_idx'), models.Index(fields=['student', 'status'], name='student_pro_student_477b50_idx'), models.Index(fields=['student', 'completed_at'], name='student_pro_student_bac145_idx')],
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report'), ('SUBJECT', 'Subject Report'), ('GRADE', 'Grade Report')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress_reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['student'], name='progress_re_student_8cbd19_idx'), models.Index(fields=['report_type'], name='progress_re_report__0a919c_idx'), models.Index(fields=['period_start'], name='progress_re_period__b0f94f_idx'), models.Index(fields=['period_end'], name='progress_re_period__eac401_idx'), models.Index(fields=['generated_at'], name='progress_re_generat_8ad853_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgressMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('LESSON_COMPLETION', 'Lesson Completion'), ('SUBJECT_COMPLETION', 'Subject Completion'), ('STREAK_ACHIEVEMENT', 'Streak Achievement'), ('SCORE_ACHIEVEMENT', 'Score Achievement'), ('TIME_ACHIEVEMENT', 'Time Achievement')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_notified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress_milestones',
                'ordering': ['-achieved_at'],
                'indexes': [models.Index(fields=['student'], name='progress_mi_student_8f2a40_idx'), models.Index(fields=['milestone_type'], name='progress_mi_milesto_60ee1b_idx'), models.Index(fields=['achieved_at'], name='progress_mi_achieve_695152_idx'), models.Index(fields=['is_notified'], name='progress_mi_is_noti_083b16_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParentDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_dashboard', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parent_dashboard',
                'indexes': [models.Index(fields=['parent'], name='parent_dash_parent__d26a87_idx'), models.Index(fields=['child'], name='parent_dash_child_i_c888a2_idx'), models.Index(fields=['last_updated'], name='parent_dash_last_up_9651a0_idx')],
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.CreateModel(
            name='LearningStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('streak_start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_streaks',
                'indexes': [models.Index(fields=['student'], name='learning_st_student_aef255_idx'), models.Index(fields=['current_streak'], name='learning_st_current_c38f25_idx'), models.Index(fields=['last_activity_date'], name='learning_st_last_ac_3fdc3d_idx')],
                'unique_together': {('student',)},
            },
        ),
        migrations.CreateModel(
            name='GradeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('total_subjects', models.IntegerField(default=0)),
                ('completed_subjects', models.IntegerField(default=0)),
                ('total_lessons', models.IntegerField(default=0)),
                ('completed_lessons', models.IntegerField(default=0)),
                ('total_quizzes', models.IntegerField(default=0)),
                ('passed_quizzes', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('overall_average', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grade_progress',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['student'], name='grade_progr_student_efd412_idx'), models.Index(fields=['grade_level'], name='grade_progr_grade_l_c935c9_idx'), models.Index(fields=['student', 'grade_level'], name='grade_progr_student_d8480e_idx')],
                'unique_together': {('student', 'grade_level')},
            },
        ),
    ]
