# Generated by Django 4.2.7 on 2025-10-21 23:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_duration', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chapters',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('content_type', models.CharField(choices=[('SLIDES', 'Slides'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('READING', 'Reading'), ('INTERACTIVE', 'Interactive')], default='SLIDES', max_length=20)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('learning_objectives', models.JSONField(blank=True, default=list)),
                ('average_rating', models.FloatField(default=0.0)),
                ('rating_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.chapter')),
                ('prerequisites', models.ManyToManyField(blank=True, to='content.lesson')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade_level', models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('is_active', models.BooleanField(default=True)),
                ('order_index', models.IntegerField(default=0)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('color_code', models.CharField(default='#007bff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['grade_level', 'order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfflineContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_url', models.URLField()),
                ('file_size', models.BigIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_content', to='content.lesson')),
            ],
            options={
                'db_table': 'offline_content',
            },
        ),
        migrations.CreateModel(
            name='LessonMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('DOCUMENT', 'Document')], max_length=20)),
                ('file_url', models.URLField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(max_length=100)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='content.lesson')),
            ],
            options={
                'db_table': 'lesson_media',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20)),
                ('content_snapshot', models.JSONField()),
                ('change_log', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.lesson')),
            ],
            options={
                'db_table': 'content_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('is_helpful', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('FREE', 'Free Access'), ('PREMIUM', 'Premium Access'), ('RESTRICTED', 'Restricted Access')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_access',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content.subject'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['grade_level'], name='subjects_grade_l_ca2342_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school'], name='subjects_school__01dc27_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active'], name='subjects_is_acti_960049_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['order_index'], name='subjects_order_i_862633_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'grade_level', 'school')},
        ),
        migrations.AddIndex(
            model_name='offlinecontent',
            index=models.Index(fields=['lesson'], name='offline_con_lesson__74f92b_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinecontent',
            index=models.Index(fields=['is_available'], name='offline_con_is_avai_762f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonmedia',
            index=models.Index(fields=['lesson'], name='lesson_medi_lesson__27a6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonmedia',
            index=models.Index(fields=['media_type'], name='lesson_medi_media_t_8e60c0_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonmedia',
            index=models.Index(fields=['order_index'], name='lesson_medi_order_i_c57261_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['chapter'], name='lessons_chapter_858b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['order_index'], name='lessons_order_i_eb8f91_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_active'], name='lessons_is_acti_cca485_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['content_type'], name='lessons_content_20a3e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('chapter', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='contentversion',
            index=models.Index(fields=['lesson'], name='content_ver_lesson__643a60_idx'),
        ),
        migrations.AddIndex(
            model_name='contentversion',
            index=models.Index(fields=['is_current'], name='content_ver_is_curr_104a5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentversion',
            unique_together={('lesson', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='contentrating',
            index=models.Index(fields=['lesson'], name='content_rat_lesson__e22b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='contentrating',
            index=models.Index(fields=['rating'], name='content_rat_rating_d501e0_idx'),
        ),
        migrations.AddIndex(
            model_name='contentrating',
            index=models.Index(fields=['created_at'], name='content_rat_created_a95f40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentrating',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='contentbookmark',
            index=models.Index(fields=['user'], name='content_boo_user_id_c821a0_idx'),
        ),
        migrations.AddIndex(
            model_name='contentbookmark',
            index=models.Index(fields=['lesson'], name='content_boo_lesson__94213d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentbookmark',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='contentaccess',
            index=models.Index(fields=['user'], name='content_acc_user_id_cf4db3_idx'),
        ),
        migrations.AddIndex(
            model_name='contentaccess',
            index=models.Index(fields=['lesson'], name='content_acc_lesson__e0204a_idx'),
        ),
        migrations.AddIndex(
            model_name='contentaccess',
            index=models.Index(fields=['access_type'], name='content_acc_access__3fec13_idx'),
        ),
        migrations.AddIndex(
            model_name='contentaccess',
            index=models.Index(fields=['is_active'], name='content_acc_is_acti_4c0ac5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentaccess',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['subject'], name='chapters_subject_5fe30d_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['order_index'], name='chapters_order_i_880a77_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['is_active'], name='chapters_is_acti_c509dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'order_index')},
        ),
    ]
