# Generated by Django 4.2.7 on 2025-10-21 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('login_count', models.IntegerField(default=0)),
                ('session_duration', models.IntegerField(default=0)),
                ('lessons_accessed', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('quizzes_attempted', models.IntegerField(default=0)),
                ('quizzes_completed', models.IntegerField(default=0)),
                ('time_spent_learning', models.IntegerField(default=0)),
                ('content_rated', models.IntegerField(default=0)),
                ('bookmarks_created', models.IntegerField(default=0)),
                ('searches_performed', models.IntegerField(default=0)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_engagement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_users', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('total_teachers', models.IntegerField(default=0)),
                ('total_parents', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_registrations', models.IntegerField(default=0)),
                ('total_lessons', models.IntegerField(default=0)),
                ('total_quizzes', models.IntegerField(default=0)),
                ('total_subjects', models.IntegerField(default=0)),
                ('content_views', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('quizzes_attempted', models.IntegerField(default=0)),
                ('quizzes_passed', models.IntegerField(default=0)),
                ('total_learning_time', models.IntegerField(default=0)),
                ('average_session_duration', models.FloatField(default=0)),
                ('average_lesson_completion_rate', models.FloatField(default=0)),
                ('average_quiz_pass_rate', models.FloatField(default=0)),
                ('page_load_time', models.FloatField(default=0)),
                ('error_rate', models.FloatField(default=0)),
                ('uptime', models.FloatField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='system_anal_date_ccb353_idx')],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='SchoolAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_students', models.IntegerField(default=0)),
                ('active_students', models.IntegerField(default=0)),
                ('engaged_students', models.IntegerField(default=0)),
                ('total_lessons_completed', models.IntegerField(default=0)),
                ('total_quizzes_attempted', models.IntegerField(default=0)),
                ('total_quizzes_passed', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('grade_1_students', models.IntegerField(default=0)),
                ('grade_2_students', models.IntegerField(default=0)),
                ('grade_3_students', models.IntegerField(default=0)),
                ('grade_4_students', models.IntegerField(default=0)),
                ('subject_performance', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='accounts.school')),
            ],
            options={
                'db_table': 'school_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.IntegerField()),
                ('total_views', models.IntegerField(default=0)),
                ('unique_viewers', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0)),
                ('average_time_spent', models.FloatField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('bookmark_count', models.IntegerField(default=0)),
                ('bounce_rate', models.FloatField(default=0)),
                ('return_visitors', models.IntegerField(default=0)),
                ('social_shares', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['content_type'], name='content_ana_content_e56409_idx'), models.Index(fields=['content_id'], name='content_ana_content_335ddd_idx'), models.Index(fields=['date'], name='content_ana_date_0ab737_idx'), models.Index(fields=['content_type', 'content_id'], name='content_ana_content_2a9764_idx')],
                'unique_together': {('content_type', 'content_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily Report'), ('WEEKLY', 'Weekly Report'), ('MONTHLY', 'Monthly Report'), ('QUARTERLY', 'Quarterly Report'), ('YEARLY', 'Yearly Report'), ('CUSTOM', 'Custom Report')], max_length=20)),
                ('report_scope', models.CharField(choices=[('SYSTEM', 'System-wide'), ('SCHOOL', 'School-level'), ('STUDENT', 'Student-level'), ('TEACHER', 'Teacher-level'), ('CONTENT', 'Content-level')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('filters', models.JSONField(default=dict)),
                ('data', models.JSONField()),
                ('summary', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, max_length=20)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('lesson_access', 'Lesson Access'), ('lesson_completion', 'Lesson Completion'), ('quiz_attempt', 'Quiz Attempt'), ('quiz_completion', 'Quiz Completion'), ('time_spent', 'Time Spent'), ('score_achieved', 'Score Achieved'), ('login_activity', 'Login Activity'), ('content_rating', 'Content Rating'), ('bookmark_created', 'Bookmark Created'), ('search_performed', 'Search Performed'), ('error_occurred', 'Error Occurred')], max_length=50)),
                ('metric_value', models.FloatField()),
                ('metadata', models.JSONField(default=dict)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.lesson')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics',
                'ordering': ['-created_at'],
            },
        ),
    ]
