# Generated by Django 4.2.7 on 2025-10-21 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('quizzes', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_records', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_records', to='accounts.school'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analytics',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.subject'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['user'], name='user_engage_user_id_8dcf23_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['date'], name='user_engage_date_d2d54b_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['user', 'date'], name='user_engage_user_id_9c9dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['device_type'], name='user_engage_device__03eb12_idx'),
        ),
        migrations.AddIndex(
            model_name='userengagement',
            index=models.Index(fields=['platform'], name='user_engage_platfor_a89c78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userengagement',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='schoolanalytics',
            index=models.Index(fields=['school'], name='school_anal_school__f5b870_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolanalytics',
            index=models.Index(fields=['date'], name='school_anal_date_7347ff_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolanalytics',
            index=models.Index(fields=['school', 'date'], name='school_anal_school__7a4c31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolanalytics',
            unique_together={('school', 'date')},
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['report_type'], name='analytics_r_report__21878c_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['report_scope'], name='analytics_r_report__150594_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['start_date'], name='analytics_r_start_d_56fb3c_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['end_date'], name='analytics_r_end_dat_f40d27_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['generated_at'], name='analytics_r_generat_c2a8d2_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['student'], name='analytics_student_71045c_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['teacher'], name='analytics_teacher_6835a6_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['parent'], name='analytics_parent__b69a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['school'], name='analytics_school__f701e2_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['subject'], name='analytics_subject_41d6db_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['lesson'], name='analytics_lesson__480332_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['quiz'], name='analytics_quiz_id_3656a3_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['metric_type'], name='analytics_metric__47877e_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['date'], name='analytics_date_f1f7af_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['created_at'], name='analytics_created_786169_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['student', 'metric_type'], name='analytics_student_163383_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['school', 'metric_type'], name='analytics_school__8d1a12_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['date', 'metric_type'], name='analytics_date_0c4d82_idx'),
        ),
    ]
