# Generated by Django 4.2.7 on 2025-10-21 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('LESSON_COMPLETED', 'Lesson Completed'), ('QUIZ_RESULT', 'Quiz Result'), ('ACHIEVEMENT', 'Achievement Unlocked'), ('STREAK_MILESTONE', 'Streak Milestone'), ('REMINDER', 'Learning Reminder'), ('SYSTEM', 'System Notification'), ('PARENT_UPDATE', 'Parent Update'), ('TEACHER_MESSAGE', 'Teacher Message'), ('CONTENT_UPDATE', 'Content Update'), ('MAINTENANCE', 'Maintenance Notice')], max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('data', models.JSONField(default=dict)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('notification_type', models.CharField(choices=[('LESSON_COMPLETED', 'Lesson Completed'), ('QUIZ_RESULT', 'Quiz Result'), ('ACHIEVEMENT', 'Achievement Unlocked'), ('STREAK_MILESTONE', 'Streak Milestone'), ('REMINDER', 'Learning Reminder'), ('SYSTEM', 'System Notification'), ('PARENT_UPDATE', 'Parent Update'), ('TEACHER_MESSAGE', 'Teacher Message'), ('CONTENT_UPDATE', 'Content Update'), ('MAINTENANCE', 'Maintenance Notice')], max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('variables', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_send', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_lesson_completed', models.BooleanField(default=True)),
                ('email_quiz_result', models.BooleanField(default=True)),
                ('email_achievement', models.BooleanField(default=True)),
                ('email_reminders', models.BooleanField(default=True)),
                ('email_system', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_lesson_completed', models.BooleanField(default=True)),
                ('push_quiz_result', models.BooleanField(default=True)),
                ('push_achievement', models.BooleanField(default=True)),
                ('push_reminders', models.BooleanField(default=True)),
                ('push_system', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('in_app_lesson_completed', models.BooleanField(default=True)),
                ('in_app_quiz_result', models.BooleanField(default=True)),
                ('in_app_achievement', models.BooleanField(default=True)),
                ('in_app_reminders', models.BooleanField(default=True)),
                ('in_app_system', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('reminder_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('NEVER', 'Never')], default='DAILY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
                'unique_together': {('user',)},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('EMAIL', 'Email'), ('PUSH', 'Push Notification'), ('SMS', 'SMS'), ('IN_APP', 'In-App')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification'], name='notificatio_notific_aabcef_idx'), models.Index(fields=['delivery_method'], name='notificatio_deliver_d4fc6e_idx'), models.Index(fields=['status'], name='notificatio_status_95b675_idx'), models.Index(fields=['delivery_time'], name='notificatio_deliver_2e1edd_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('campaign_type', models.CharField(choices=[('BROADCAST', 'Broadcast'), ('TARGETED', 'Targeted'), ('SCHEDULED', 'Scheduled'), ('TRIGGERED', 'Triggered')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('LESSON_COMPLETED', 'Lesson Completed'), ('QUIZ_RESULT', 'Quiz Result'), ('ACHIEVEMENT', 'Achievement Unlocked'), ('STREAK_MILESTONE', 'Streak Milestone'), ('REMINDER', 'Learning Reminder'), ('SYSTEM', 'System Notification'), ('PARENT_UPDATE', 'Parent Update'), ('TEACHER_MESSAGE', 'Teacher Message'), ('CONTENT_UPDATE', 'Content Update'), ('MAINTENANCE', 'Maintenance Notice')], max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('target_users', models.JSONField(default=dict)),
                ('target_count', models.IntegerField(default=0)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_campaigns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign_type'], name='notificatio_campaig_283e56_idx'), models.Index(fields=['status'], name='notificatio_status_0adad2_idx'), models.Index(fields=['scheduled_for'], name='notificatio_schedul_7cfdee_idx'), models.Index(fields=['created_by'], name='notificatio_created_327d05_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='notificatio_user_id_e78525_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_17ee5f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_sent'], name='notificatio_is_sent_7b3d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for'], name='notificatio_schedul_3d00b6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_66996e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_63f199_idx'),
        ),
    ]
